[package]
name = "contour-to-boxes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contour = {version = "0.12.0", features = ["f32"]}
rten-imageproc = "0.4.0"
tiny-skia = "0.11.4"
